name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - branch1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Flutter Web App
        run: |
          flutter pub get
          flutter build web --base-href "/"

      - name: Preserve Custom Domain
        run: echo "santiagosfurniture.page" > build/web/CNAME

      - name: Push Compiled Files to GitHub Pages Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build/web'
          destination-github-username: 'blair04'
          destination-repository-name: 'blair04.github.io'
          user-email: 'gracejoylibrea@gmail.com' # Change to your actual email
          target-branch: 'main'
